-----------------------------------------------------------------------------
--   Copyright (C) 2018 by Christoph Thelen                                --
--   doc_bacardi@users.sourceforge.net                                     --
--                                                                         --
--   This program is free software; you can redistribute it and/or modify  --
--   it under the terms of the GNU General Public License as published by  --
--   the Free Software Foundation; either version 2 of the License, or     --
--   (at your option) any later version.                                   --
--                                                                         --
--   This program is distributed in the hope that it will be useful,       --
--   but WITHOUT ANY WARRANTY; without even the implied warranty of        --
--   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         --
--   GNU General Public License for more details.                          --
--                                                                         --
--   You should have received a copy of the GNU General Public License     --
--   along with this program; if not, write to the                         --
--   Free Software Foundation, Inc.,                                       --
--   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             --
-----------------------------------------------------------------------------

local class = require 'pl.class'
local IoMatrix_netx_base = require 'io_matrix.netx_base'
local IoMatrix_netx4000 = class(IoMatrix_netx_base)


function IoMatrix_netx4000:_init(tLog, fnInit, fnDeinit, ulVerbose, fnCallbackProgress, fnCallbackMessage)
  self:super(tLog, fnInit, fnDeinit, ulVerbose, fnCallbackProgress, fnCallbackMessage)
end



IoMatrix_netx4000.atKnownPins = {
  ['MMIO0'] = { type=${PINTYPE_MMIO}, index=0 },
  ['MMIO1'] = { type=${PINTYPE_MMIO}, index=1 },
  ['MMIO2'] = { type=${PINTYPE_MMIO}, index=2 },
  ['MMIO3'] = { type=${PINTYPE_MMIO}, index=3 },
  ['MMIO4'] = { type=${PINTYPE_MMIO}, index=4 },
  ['MMIO5'] = { type=${PINTYPE_MMIO}, index=5 },
  ['MMIO6'] = { type=${PINTYPE_MMIO}, index=6 },
  ['MMIO7'] = { type=${PINTYPE_MMIO}, index=7 },
  ['MMIO8'] = { type=${PINTYPE_MMIO}, index=8 },
  ['MMIO9'] = { type=${PINTYPE_MMIO}, index=9 },
  ['MMIO10'] = { type=${PINTYPE_MMIO}, index=10 },
  ['MMIO11'] = { type=${PINTYPE_MMIO}, index=11 },
  ['MMIO12'] = { type=${PINTYPE_MMIO}, index=12 },
  ['MMIO13'] = { type=${PINTYPE_MMIO}, index=13 },
  ['MMIO14'] = { type=${PINTYPE_MMIO}, index=14 },
  ['MMIO15'] = { type=${PINTYPE_MMIO}, index=15 },
  ['MMIO16'] = { type=${PINTYPE_MMIO}, index=16 },
  ['MMIO17'] = { type=${PINTYPE_MMIO}, index=17 },
  ['MMIO18'] = { type=${PINTYPE_MMIO}, index=18 },
  ['MMIO19'] = { type=${PINTYPE_MMIO}, index=19 },
  ['MMIO20'] = { type=${PINTYPE_MMIO}, index=20 },
  ['MMIO21'] = { type=${PINTYPE_MMIO}, index=21 },
  ['MMIO22'] = { type=${PINTYPE_MMIO}, index=22 },
  ['MMIO23'] = { type=${PINTYPE_MMIO}, index=23 },
  ['MMIO24'] = { type=${PINTYPE_MMIO}, index=24 },
  ['MMIO25'] = { type=${PINTYPE_MMIO}, index=25 },
  ['MMIO26'] = { type=${PINTYPE_MMIO}, index=26 },
  ['MMIO27'] = { type=${PINTYPE_MMIO}, index=27 },
  ['MMIO28'] = { type=${PINTYPE_MMIO}, index=28 },
  ['MMIO29'] = { type=${PINTYPE_MMIO}, index=29 },
  ['MMIO30'] = { type=${PINTYPE_MMIO}, index=30 },
  ['MMIO31'] = { type=${PINTYPE_MMIO}, index=31 },
  ['MMIO32'] = { type=${PINTYPE_MMIO}, index=32 },
  ['MMIO33'] = { type=${PINTYPE_MMIO}, index=33 },
  ['MMIO34'] = { type=${PINTYPE_MMIO}, index=34 },
  ['MMIO35'] = { type=${PINTYPE_MMIO}, index=35 },
  ['MMIO36'] = { type=${PINTYPE_MMIO}, index=36 },
  ['MMIO37'] = { type=${PINTYPE_MMIO}, index=37 },
  ['MMIO38'] = { type=${PINTYPE_MMIO}, index=38 },
  ['MMIO39'] = { type=${PINTYPE_MMIO}, index=39 },
  ['MMIO40'] = { type=${PINTYPE_MMIO}, index=40 },
  ['MMIO41'] = { type=${PINTYPE_MMIO}, index=41 },
  ['MMIO42'] = { type=${PINTYPE_MMIO}, index=42 },
  ['MMIO43'] = { type=${PINTYPE_MMIO}, index=43 },
  ['MMIO44'] = { type=${PINTYPE_MMIO}, index=44 },
  ['MMIO45'] = { type=${PINTYPE_MMIO}, index=45 },
  ['MMIO46'] = { type=${PINTYPE_MMIO}, index=46 },
  ['MMIO47'] = { type=${PINTYPE_MMIO}, index=47 },
  ['MMIO48'] = { type=${PINTYPE_MMIO}, index=48 },
  ['MMIO49'] = { type=${PINTYPE_MMIO}, index=49 },
  ['MMIO50'] = { type=${PINTYPE_MMIO}, index=50 },
  ['MMIO51'] = { type=${PINTYPE_MMIO}, index=51 },
  ['MMIO52'] = { type=${PINTYPE_MMIO}, index=52 },
  ['MMIO53'] = { type=${PINTYPE_MMIO}, index=53 },
  ['MMIO54'] = { type=${PINTYPE_MMIO}, index=54 },
  ['MMIO55'] = { type=${PINTYPE_MMIO}, index=55 },
  ['MMIO56'] = { type=${PINTYPE_MMIO}, index=56 },
  ['MMIO57'] = { type=${PINTYPE_MMIO}, index=57 },
  ['MMIO58'] = { type=${PINTYPE_MMIO}, index=58 },
  ['MMIO59'] = { type=${PINTYPE_MMIO}, index=59 },
  ['MMIO60'] = { type=${PINTYPE_MMIO}, index=60 },
  ['MMIO61'] = { type=${PINTYPE_MMIO}, index=61 },
  ['MMIO62'] = { type=${PINTYPE_MMIO}, index=62 },
  ['MMIO63'] = { type=${PINTYPE_MMIO}, index=63 },
  ['MMIO64'] = { type=${PINTYPE_MMIO}, index=64 },
  ['MMIO65'] = { type=${PINTYPE_MMIO}, index=65 },
  ['MMIO66'] = { type=${PINTYPE_MMIO}, index=66 },
  ['MMIO67'] = { type=${PINTYPE_MMIO}, index=67 },
  ['MMIO68'] = { type=${PINTYPE_MMIO}, index=68 },
  ['MMIO69'] = { type=${PINTYPE_MMIO}, index=69 },
  ['MMIO70'] = { type=${PINTYPE_MMIO}, index=70 },
  ['MMIO71'] = { type=${PINTYPE_MMIO}, index=71 },
  ['MMIO72'] = { type=${PINTYPE_MMIO}, index=72 },
  ['MMIO73'] = { type=${PINTYPE_MMIO}, index=73 },
  ['MMIO74'] = { type=${PINTYPE_MMIO}, index=74 },
  ['MMIO75'] = { type=${PINTYPE_MMIO}, index=75 },
  ['MMIO76'] = { type=${PINTYPE_MMIO}, index=76 },
  ['MMIO77'] = { type=${PINTYPE_MMIO}, index=77 },
  ['MMIO78'] = { type=${PINTYPE_MMIO}, index=78 },
  ['MMIO79'] = { type=${PINTYPE_MMIO}, index=79 },
  ['MMIO80'] = { type=${PINTYPE_MMIO}, index=80 },
  ['MMIO81'] = { type=${PINTYPE_MMIO}, index=81 },
  ['MMIO82'] = { type=${PINTYPE_MMIO}, index=82 },
  ['MMIO83'] = { type=${PINTYPE_MMIO}, index=83 },
  ['MMIO84'] = { type=${PINTYPE_MMIO}, index=84 },
  ['MMIO85'] = { type=${PINTYPE_MMIO}, index=85 },
  ['MMIO86'] = { type=${PINTYPE_MMIO}, index=86 },
  ['MMIO87'] = { type=${PINTYPE_MMIO}, index=87 },
  ['MMIO88'] = { type=${PINTYPE_MMIO}, index=88 },
  ['MMIO89'] = { type=${PINTYPE_MMIO}, index=89 },
  ['MMIO90'] = { type=${PINTYPE_MMIO}, index=90 },
  ['MMIO91'] = { type=${PINTYPE_MMIO}, index=91 },
  ['MMIO92'] = { type=${PINTYPE_MMIO}, index=92 },
  ['MMIO93'] = { type=${PINTYPE_MMIO}, index=93 },
  ['MMIO94'] = { type=${PINTYPE_MMIO}, index=94 },
  ['MMIO95'] = { type=${PINTYPE_MMIO}, index=95 },
  ['MMIO96'] = { type=${PINTYPE_MMIO}, index=96 },
  ['MMIO97'] = { type=${PINTYPE_MMIO}, index=97 },
  ['MMIO98'] = { type=${PINTYPE_MMIO}, index=98 },
  ['MMIO99'] = { type=${PINTYPE_MMIO}, index=99 },
  ['MMIO100'] = { type=${PINTYPE_MMIO}, index=100 },
  ['MMIO101'] = { type=${PINTYPE_MMIO}, index=101 },
  ['MMIO102'] = { type=${PINTYPE_MMIO}, index=102 },
  ['MMIO103'] = { type=${PINTYPE_MMIO}, index=103 },
  ['MMIO104'] = { type=${PINTYPE_MMIO}, index=104 },
  ['MMIO105'] = { type=${PINTYPE_MMIO}, index=105 },
  ['MMIO106'] = { type=${PINTYPE_MMIO}, index=106 },

  ['RDY'] = { type=${PINTYPE_RDYRUN}, index=0 },
  ['RUN'] = { type=${PINTYPE_RDYRUN}, index=1 },

  ['RAPGPIO0_0'] = { type=${PINTYPE_RAPGPIO}, index=0 },
  ['RAPGPIO0_1'] = { type=${PINTYPE_RAPGPIO}, index=1 },
  ['RAPGPIO0_2'] = { type=${PINTYPE_RAPGPIO}, index=2 },
  ['RAPGPIO0_3'] = { type=${PINTYPE_RAPGPIO}, index=3 },
  ['RAPGPIO0_4'] = { type=${PINTYPE_RAPGPIO}, index=4 },
  ['RAPGPIO0_5'] = { type=${PINTYPE_RAPGPIO}, index=5 },
  ['RAPGPIO0_6'] = { type=${PINTYPE_RAPGPIO}, index=6 },
  ['RAPGPIO0_7'] = { type=${PINTYPE_RAPGPIO}, index=7 },
  ['RAPGPIO0_8'] = { type=${PINTYPE_RAPGPIO}, index=8 },
  ['RAPGPIO0_9'] = { type=${PINTYPE_RAPGPIO}, index=9 },
  ['RAPGPIO0_10'] = { type=${PINTYPE_RAPGPIO}, index=10 },
  ['RAPGPIO0_11'] = { type=${PINTYPE_RAPGPIO}, index=11 },
  ['RAPGPIO0_12'] = { type=${PINTYPE_RAPGPIO}, index=12 },
  ['RAPGPIO0_13'] = { type=${PINTYPE_RAPGPIO}, index=13 },
  ['RAPGPIO0_14'] = { type=${PINTYPE_RAPGPIO}, index=14 },
  ['RAPGPIO0_15'] = { type=${PINTYPE_RAPGPIO}, index=15 },
  ['RAPGPIO0_16'] = { type=${PINTYPE_RAPGPIO}, index=16 },
  ['RAPGPIO0_17'] = { type=${PINTYPE_RAPGPIO}, index=17 },
  ['RAPGPIO0_18'] = { type=${PINTYPE_RAPGPIO}, index=18 },
  ['RAPGPIO0_19'] = { type=${PINTYPE_RAPGPIO}, index=19 },
  ['RAPGPIO0_20'] = { type=${PINTYPE_RAPGPIO}, index=20 },
  ['RAPGPIO0_21'] = { type=${PINTYPE_RAPGPIO}, index=21 },
  ['RAPGPIO0_22'] = { type=${PINTYPE_RAPGPIO}, index=22 },
  ['RAPGPIO0_23'] = { type=${PINTYPE_RAPGPIO}, index=23 },

  ['RAPGPIO1_0'] = { type=${PINTYPE_RAPGPIO}, index=32 },
  ['RAPGPIO1_1'] = { type=${PINTYPE_RAPGPIO}, index=33 },
  ['RAPGPIO1_2'] = { type=${PINTYPE_RAPGPIO}, index=34 },
  ['RAPGPIO1_3'] = { type=${PINTYPE_RAPGPIO}, index=35 },
  ['RAPGPIO1_4'] = { type=${PINTYPE_RAPGPIO}, index=36 },
  ['RAPGPIO1_5'] = { type=${PINTYPE_RAPGPIO}, index=37 },
  ['RAPGPIO1_6'] = { type=${PINTYPE_RAPGPIO}, index=38 },
  ['RAPGPIO1_7'] = { type=${PINTYPE_RAPGPIO}, index=39 },
  ['RAPGPIO1_8'] = { type=${PINTYPE_RAPGPIO}, index=40 },
  ['RAPGPIO1_9'] = { type=${PINTYPE_RAPGPIO}, index=41 },
  ['RAPGPIO1_10'] = { type=${PINTYPE_RAPGPIO}, index=42 },
  ['RAPGPIO1_11'] = { type=${PINTYPE_RAPGPIO}, index=43 },
  ['RAPGPIO1_12'] = { type=${PINTYPE_RAPGPIO}, index=44 },
  ['RAPGPIO1_13'] = { type=${PINTYPE_RAPGPIO}, index=45 },
  ['RAPGPIO1_14'] = { type=${PINTYPE_RAPGPIO}, index=46 },
  ['RAPGPIO1_15'] = { type=${PINTYPE_RAPGPIO}, index=47 },
  ['RAPGPIO1_16'] = { type=${PINTYPE_RAPGPIO}, index=48 },
  ['RAPGPIO1_17'] = { type=${PINTYPE_RAPGPIO}, index=49 },
  ['RAPGPIO1_18'] = { type=${PINTYPE_RAPGPIO}, index=50 },
  ['RAPGPIO1_19'] = { type=${PINTYPE_RAPGPIO}, index=51 },
  ['RAPGPIO1_20'] = { type=${PINTYPE_RAPGPIO}, index=52 },
  ['RAPGPIO1_21'] = { type=${PINTYPE_RAPGPIO}, index=53 },
  ['RAPGPIO1_22'] = { type=${PINTYPE_RAPGPIO}, index=54 },
  ['RAPGPIO1_23'] = { type=${PINTYPE_RAPGPIO}, index=55 },
  ['RAPGPIO1_24'] = { type=${PINTYPE_RAPGPIO}, index=56 },
  ['RAPGPIO1_25'] = { type=${PINTYPE_RAPGPIO}, index=57 },

  ['RAPGPIO2_0'] = { type=${PINTYPE_RAPGPIO}, index=64 },
  ['RAPGPIO2_1'] = { type=${PINTYPE_RAPGPIO}, index=65 },
  ['RAPGPIO2_2'] = { type=${PINTYPE_RAPGPIO}, index=66 },
  ['RAPGPIO2_3'] = { type=${PINTYPE_RAPGPIO}, index=67 },
  ['RAPGPIO2_4'] = { type=${PINTYPE_RAPGPIO}, index=68 },
  ['RAPGPIO2_5'] = { type=${PINTYPE_RAPGPIO}, index=69 },
  ['RAPGPIO2_6'] = { type=${PINTYPE_RAPGPIO}, index=70 },
  ['RAPGPIO2_7'] = { type=${PINTYPE_RAPGPIO}, index=71 },
  ['RAPGPIO2_8'] = { type=${PINTYPE_RAPGPIO}, index=72 },
  ['RAPGPIO2_9'] = { type=${PINTYPE_RAPGPIO}, index=73 },
  ['RAPGPIO2_10'] = { type=${PINTYPE_RAPGPIO}, index=74 },
  ['RAPGPIO2_11'] = { type=${PINTYPE_RAPGPIO}, index=75 },
  ['RAPGPIO2_12'] = { type=${PINTYPE_RAPGPIO}, index=76 },
  ['RAPGPIO2_13'] = { type=${PINTYPE_RAPGPIO}, index=77 },
  ['RAPGPIO2_14'] = { type=${PINTYPE_RAPGPIO}, index=78 },
  ['RAPGPIO2_15'] = { type=${PINTYPE_RAPGPIO}, index=79 },
  ['RAPGPIO2_16'] = { type=${PINTYPE_RAPGPIO}, index=80 },
  ['RAPGPIO2_17'] = { type=${PINTYPE_RAPGPIO}, index=81 },
  ['RAPGPIO2_18'] = { type=${PINTYPE_RAPGPIO}, index=82 },
  ['RAPGPIO2_19'] = { type=${PINTYPE_RAPGPIO}, index=83 },
  ['RAPGPIO2_20'] = { type=${PINTYPE_RAPGPIO}, index=84 },
  ['RAPGPIO2_21'] = { type=${PINTYPE_RAPGPIO}, index=85 },
  ['RAPGPIO2_22'] = { type=${PINTYPE_RAPGPIO}, index=86 },
  ['RAPGPIO2_23'] = { type=${PINTYPE_RAPGPIO}, index=87 },
  ['RAPGPIO2_24'] = { type=${PINTYPE_RAPGPIO}, index=88 },
  ['RAPGPIO2_25'] = { type=${PINTYPE_RAPGPIO}, index=89 },
  ['RAPGPIO2_26'] = { type=${PINTYPE_RAPGPIO}, index=90 },
  ['RAPGPIO2_27'] = { type=${PINTYPE_RAPGPIO}, index=91 },
  ['RAPGPIO2_28'] = { type=${PINTYPE_RAPGPIO}, index=92 },
  ['RAPGPIO2_29'] = { type=${PINTYPE_RAPGPIO}, index=93 },
  ['RAPGPIO2_30'] = { type=${PINTYPE_RAPGPIO}, index=94 },
  ['RAPGPIO2_31'] = { type=${PINTYPE_RAPGPIO}, index=95 },

  ['RAPGPIO3_0'] = { type=${PINTYPE_RAPGPIO}, index=96 },
  ['RAPGPIO3_1'] = { type=${PINTYPE_RAPGPIO}, index=97 },
  ['RAPGPIO3_2'] = { type=${PINTYPE_RAPGPIO}, index=98 },
  ['RAPGPIO3_3'] = { type=${PINTYPE_RAPGPIO}, index=99 },
  ['RAPGPIO3_4'] = { type=${PINTYPE_RAPGPIO}, index=100 },
  ['RAPGPIO3_5'] = { type=${PINTYPE_RAPGPIO}, index=101 },
  ['RAPGPIO3_6'] = { type=${PINTYPE_RAPGPIO}, index=102 },
  ['RAPGPIO3_7'] = { type=${PINTYPE_RAPGPIO}, index=103 },
  ['RAPGPIO3_8'] = { type=${PINTYPE_RAPGPIO}, index=104 },
  ['RAPGPIO3_9'] = { type=${PINTYPE_RAPGPIO}, index=105 },
  ['RAPGPIO3_10'] = { type=${PINTYPE_RAPGPIO}, index=106 },
  ['RAPGPIO3_11'] = { type=${PINTYPE_RAPGPIO}, index=107 },
  ['RAPGPIO3_12'] = { type=${PINTYPE_RAPGPIO}, index=108 },
  ['RAPGPIO3_13'] = { type=${PINTYPE_RAPGPIO}, index=109 },
  ['RAPGPIO3_14'] = { type=${PINTYPE_RAPGPIO}, index=110 },
  ['RAPGPIO3_15'] = { type=${PINTYPE_RAPGPIO}, index=111 },
  ['RAPGPIO3_16'] = { type=${PINTYPE_RAPGPIO}, index=112 },
  ['RAPGPIO3_17'] = { type=${PINTYPE_RAPGPIO}, index=113 },
  ['RAPGPIO3_18'] = { type=${PINTYPE_RAPGPIO}, index=114 },
  ['RAPGPIO3_19'] = { type=${PINTYPE_RAPGPIO}, index=115 },
  ['RAPGPIO3_20'] = { type=${PINTYPE_RAPGPIO}, index=116 },
  ['RAPGPIO3_21'] = { type=${PINTYPE_RAPGPIO}, index=117 },
  ['RAPGPIO3_22'] = { type=${PINTYPE_RAPGPIO}, index=118 },
  ['RAPGPIO3_23'] = { type=${PINTYPE_RAPGPIO}, index=119 },
  ['RAPGPIO3_24'] = { type=${PINTYPE_RAPGPIO}, index=120 },
  ['RAPGPIO3_25'] = { type=${PINTYPE_RAPGPIO}, index=121 },
  ['RAPGPIO3_26'] = { type=${PINTYPE_RAPGPIO}, index=122 },
  ['RAPGPIO3_27'] = { type=${PINTYPE_RAPGPIO}, index=123 },
  ['RAPGPIO3_28'] = { type=${PINTYPE_RAPGPIO}, index=124 },
  ['RAPGPIO3_29'] = { type=${PINTYPE_RAPGPIO}, index=125 },
  ['RAPGPIO3_30'] = { type=${PINTYPE_RAPGPIO}, index=126 },

  ['RAPGPIO4_0'] = { type=${PINTYPE_RAPGPIO}, index=128 },
  ['RAPGPIO4_1'] = { type=${PINTYPE_RAPGPIO}, index=129 },
  ['RAPGPIO4_2'] = { type=${PINTYPE_RAPGPIO}, index=130 },
  ['RAPGPIO4_3'] = { type=${PINTYPE_RAPGPIO}, index=131 },
  ['RAPGPIO4_4'] = { type=${PINTYPE_RAPGPIO}, index=132 },
  ['RAPGPIO4_5'] = { type=${PINTYPE_RAPGPIO}, index=133 },
  ['RAPGPIO4_6'] = { type=${PINTYPE_RAPGPIO}, index=134 },
  ['RAPGPIO4_7'] = { type=${PINTYPE_RAPGPIO}, index=135 },
  ['RAPGPIO4_8'] = { type=${PINTYPE_RAPGPIO}, index=136 },
  ['RAPGPIO4_9'] = { type=${PINTYPE_RAPGPIO}, index=137 },
  ['RAPGPIO4_10'] = { type=${PINTYPE_RAPGPIO}, index=138 },
  ['RAPGPIO4_11'] = { type=${PINTYPE_RAPGPIO}, index=139 },
  ['RAPGPIO4_12'] = { type=${PINTYPE_RAPGPIO}, index=140 },
  ['RAPGPIO4_13'] = { type=${PINTYPE_RAPGPIO}, index=141 },
  ['RAPGPIO4_14'] = { type=${PINTYPE_RAPGPIO}, index=142 },
  ['RAPGPIO4_15'] = { type=${PINTYPE_RAPGPIO}, index=143 },
  ['RAPGPIO4_16'] = { type=${PINTYPE_RAPGPIO}, index=144 },
  ['RAPGPIO4_17'] = { type=${PINTYPE_RAPGPIO}, index=145 },
  ['RAPGPIO4_18'] = { type=${PINTYPE_RAPGPIO}, index=146 },
  ['RAPGPIO4_19'] = { type=${PINTYPE_RAPGPIO}, index=147 },
  ['RAPGPIO4_20'] = { type=${PINTYPE_RAPGPIO}, index=148 },
  ['RAPGPIO4_21'] = { type=${PINTYPE_RAPGPIO}, index=149 },
  ['RAPGPIO4_22'] = { type=${PINTYPE_RAPGPIO}, index=150 },
  ['RAPGPIO4_23'] = { type=${PINTYPE_RAPGPIO}, index=151 },
  ['RAPGPIO4_24'] = { type=${PINTYPE_RAPGPIO}, index=152 },
  ['RAPGPIO4_25'] = { type=${PINTYPE_RAPGPIO}, index=153 },
  ['RAPGPIO4_26'] = { type=${PINTYPE_RAPGPIO}, index=154 },
  ['RAPGPIO4_27'] = { type=${PINTYPE_RAPGPIO}, index=155 }
}



return IoMatrix_netx4000
